spring:
  application:
    name: draw
  config:
    activate:
      on-profile: prod
    import: aws-parameterstore:/config/draw_prod/
  data:
    redis:
      port: ${redis.port}
      host: ${redis.host}
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    producer:
      bootstrap-servers: ${kafka.bootstrap-server}
    consumer:
      bootstrap-servers: ${kafka.bootstrap-server}
uri:
  prize_server: ${prize.url}