### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

POST http://localhost:8080/prize
content-type: application/json

{
    "name": "Test Prize",
    "quantity": 10,
    "price": 100,
    "probabilityRange": 1000

}
#####
GET http://localhost:8080/prize/?page=-1&size=2
#######
GET http://localhost:8080/prize/3
