###
POST http://localhost:8080/prize
Content-Type: application/json

{
	 "name": "Test Prize",
	"quantity" : 1,
	"price" : 100,
	"probabilityRange" :1000

}
###
PATCH http://localhost:8080/prize
Content-Type: application/json

{
	"id": 1,
	"quantity": 2
}
###
